### ISSUE TITLE
can you help Awesome

### ISSUE THREAD

**Issue by batmanm0b1E** [isaacwhanson/dotfiles#2]
I saw your screenshot here
https://www.reddit.com/r/unixporn/comments/69rnba/i3gaps_workbox/

I love the transparent how did you do it if you can help me please. I grabbed your dotfiles and i3blocks but some stuff doesn't show if you don't mind helping Thank you

**Comment by isaacwhanson** [comment]
In I3-gaps you can specify the alpha value in the colors specified. Easy as that

**Comment by batmanm0b1E** [comment]
Hi thanks for replying. going to close this its solved now
